#!/usr/bin/env python3
"""Tool for working with the prebuilt-APK config (config/microg-apks.yaml).

Subcommands:

    apks-tool.py list-downloads
        Emit one TSV row per APK with `filename<TAB>url<TAB>sha256` —
        consumed by scripts/10-fetch-microg.sh to drive downloads.

    apks-tool.py generate-android-mk
        Emit a vendor/microg/Android.mk to stdout. Each YAML entry becomes
        one BUILD_PREBUILT block; per-module LOCAL_CERTIFICATE and
        LOCAL_PRIVILEGED_MODULE come from the YAML.

    apks-tool.py generate-microg-mk
        Emit a vendor/microg/microg.mk to stdout. Dynamic PRODUCT_PACKAGES
        from the YAML + a static PRODUCT_COPY_FILES block for the GmsCore
        privapp-permissions XML.
"""

import sys
from pathlib import Path

import yaml

CONFIG = Path(__file__).resolve().parent.parent / "config" / "microg-apks.yaml"

REQUIRED_FIELDS = ["module", "filename", "url", "sha256", "certificate", "privileged"]
VALID_CERTIFICATES = {"platform", "PRESIGNED"}


def load_apks():
    with CONFIG.open() as f:
        data = yaml.safe_load(f)
    apks = data.get("apks") or []
    for i, apk in enumerate(apks):
        missing = [f for f in REQUIRED_FIELDS if f not in apk]
        if missing:
            sys.exit(f"microg-apks.yaml entry #{i} missing fields: {', '.join(missing)}")
        if apk["certificate"] not in VALID_CERTIFICATES:
            sys.exit(
                f"microg-apks.yaml entry #{i} ({apk['module']}): "
                f"certificate must be one of {sorted(VALID_CERTIFICATES)}, "
                f"got {apk['certificate']!r}"
            )
    return apks


def cmd_list_downloads():
    for apk in load_apks():
        print(f"{apk['filename']}\t{apk['url']}\t{apk['sha256']}")


def cmd_generate_android_mk():
    print("# AUTO-GENERATED from config/microg-apks.yaml by scripts/apks-tool.py.")
    print("# Do not edit this file by hand — it is regenerated on every build.")
    print()
    print("LOCAL_PATH := $(call my-dir)")
    for apk in load_apks():
        print()
        note = apk.get("note")
        if note:
            print(f"# {apk['module']}: {note}")
        print("include $(CLEAR_VARS)")
        print(f"LOCAL_MODULE             := {apk['module']}")
        print("LOCAL_MODULE_CLASS       := APPS")
        print("LOCAL_MODULE_TAGS        := optional")
        print(f"LOCAL_SRC_FILES          := prebuilts/{apk['filename']}")
        print(f"LOCAL_CERTIFICATE        := {apk['certificate']}")
        if apk.get("privileged"):
            print("LOCAL_PRIVILEGED_MODULE  := true")
        print("LOCAL_PRODUCT_MODULE     := true")
        print("include $(BUILD_PREBUILT)")


def cmd_generate_microg_mk():
    apks = load_apks()
    print("# AUTO-GENERATED from config/microg-apks.yaml by scripts/apks-tool.py.")
    print("# Do not edit this file by hand — it is regenerated on every build.")
    print()
    print("# Add microG and FLOSS apps to the product image.")
    print("PRODUCT_PACKAGES += \\")
    for i, apk in enumerate(apks):
        terminator = " \\" if i < len(apks) - 1 else ""
        print(f"    {apk['module']}{terminator}")
    print()
    # Static block — not per-APK metadata. The privapp-permissions XML is
    # specifically about granting FAKE_PACKAGE_SIGNATURE to GmsCore; if other
    # APKs ever need similar grants, add a second static block here rather
    # than turning this into a per-APK "extras" field in the YAML.
    print("# Install the privapp-permissions file that grants FAKE_PACKAGE_SIGNATURE")
    print("# to com.google.android.gms (i.e. GmsCore). Without this the framework")
    print("# will not honour the permission even though the APK declares it.")
    print("PRODUCT_COPY_FILES += \\")
    print("    vendor/microg/permissions/privapp-permissions-com.google.android.gms.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.google.android.gms.xml")


def main():
    cmds = {
        "list-downloads": cmd_list_downloads,
        "generate-android-mk": cmd_generate_android_mk,
        "generate-microg-mk": cmd_generate_microg_mk,
    }
    args = sys.argv[1:]
    if not args or args[0] not in cmds:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    cmds[args[0]]()


if __name__ == "__main__":
    main()
