#!/usr/bin/env python3
"""Tool for working with the pinned-project config (config/pins.yaml).

Subcommands:

    pins-tool.py generate-manifest
        Emit a repo local-manifest XML to stdout — one
        <remove-project> + <project> pair per pin. Used by step 00.

    pins-tool.py field <name-or-path> <field>
        Print one field of one pin, looked up by `name` or `path`. Used
        by bash to pull individual values (e.g. the lineage_build_unified
        revision needed by the upstream-treble.xml bootstrap URL).

    pins-tool.py list
        Print one TSV row per pin with every field, in the order:
            name, path, remote, revision,
            tracking_branch, upstream_url, category, note
        Used by bash iteration in step 00's drift check.
"""

import sys
from pathlib import Path

import yaml

CONFIG = Path(__file__).resolve().parent.parent / "config" / "pins.yaml"

FIELDS = [
    "name", "path", "remote", "revision",
    "tracking_branch", "upstream_url", "category", "note",
]


def load_pins():
    with CONFIG.open() as f:
        data = yaml.safe_load(f)
    pins = data.get("pins") or []
    for i, pin in enumerate(pins):
        missing = [f for f in FIELDS if not pin.get(f)]
        if missing:
            sys.exit(f"pins.yaml entry #{i} missing fields: {', '.join(missing)}")
    return pins


def cmd_generate_manifest():
    print('<?xml version="1.0" encoding="UTF-8"?>')
    print('<!-- AUTO-GENERATED from config/pins.yaml by scripts/pins-tool.py.')
    print('     Do not edit this file by hand — it is regenerated on every build. -->')
    print('<manifest>')
    for pin in load_pins():
        print(f'  <!-- {pin["category"]}: {pin["note"]} -->')
        print(f'  <remove-project name="{pin["name"]}" />')
        print(
            f'  <project name="{pin["name"]}" '
            f'path="{pin["path"]}" '
            f'remote="{pin["remote"]}" '
            f'revision="{pin["revision"]}" />'
        )
    print('</manifest>')


def cmd_field(key, field):
    if field not in FIELDS:
        sys.exit(f"unknown field: {field} (valid: {', '.join(FIELDS)})")
    for pin in load_pins():
        if pin["name"] == key or pin["path"] == key:
            print(pin[field])
            return
    sys.exit(f"no pin found for: {key}")


def cmd_list():
    for pin in load_pins():
        print("\t".join(str(pin[f]) for f in FIELDS))


def main():
    cmds = {
        "generate-manifest": (cmd_generate_manifest, 0),
        "field": (cmd_field, 2),
        "list": (cmd_list, 0),
    }
    args = sys.argv[1:]
    if not args or args[0] not in cmds:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    fn, want_args = cmds[args[0]]
    if len(args) - 1 != want_args:
        sys.exit(f"{args[0]}: expected {want_args} argument(s), got {len(args) - 1}")
    fn(*args[1:])


if __name__ == "__main__":
    main()
